/*
 * responder.h
 *
 *  Created on: 27 мая 2018 г.
 *      Author: Dbaranov
 */

#ifndef RESPONDER_H_
#define RESPONDER_H_

#include <stdio.h>

/*max length of a string generated by sprintf in 4 functions below*/
#define OUTPUT_LENGTH 64
/*
 * Dummy function
 * Prints its arguments
 * */
void single_key_pressed(char key);

/*
 * Dummy function
 * Prints its arguments
 * */
void double_key_pressed(char key, char key2);

/*
 * Dummy function
 * Prints its arguments
 * */
void single_key_long_pressed(char key);

/*
 * Dummy function
 * Prints its arguments
 * */
void double_key_long_pressed(char key, char key2);

#endif /* RESPONDER_H_ */
